# Write a program to accept marks of 6 students and display them in a sorted manner. 
Marks = [] # This will create an empty list to store the marks
s1 = int(input("Enter the marks of student 1: ")) 
Marks.append(s1) 
s2 = int(input("Enter the marks of student 2: ")) 
Marks.append(s2) 
s3 = int(input("Enter the marks of student 3: ")) 
Marks.append(s3) 
s4 = int(input("Enter the marks of student 4: ")) 
Marks.append(s4) 
s5 = int(input("Enter the marks of student 5: ")) 
Marks.append(s5) 
s6 = int(input("Enter the marks of student 6: ")) 
Marks.append(s6) 
Marks.sort() 
print("The sorted marks are:", Marks)